### ISSUE TITLE
hideAxes issue: Cannot read 'type' of undefined

### ISSUE THREAD

**Issue by wraseman** [joshhjacobson/parasol#14]
@joshhjacobson, every time I try to hide the rightmost column (I know b/c I tried reordering the columns in the csv), I get the following error: 

![image](https://user-images.githubusercontent.com/14048152/47665244-44aaee00-db66-11e8-9722-f91dc707cd83.png)

Any thoughts on why this might be?

**Comment by wraseman** [comment]
Hmm this problem might be more complicated than I thought. I'm having more extensive issues when try to hide axes across plots. Let's discuss this bug in person.

**Comment by joshhjacobson** [comment]
Off the top of my head, I remember that when setting up the `partition` example, including the rightmost axis in the array of hidden axis for the first chart (id = 0) created this problem. Still not sure why, but this might be a good place to start looking.

**Comment by joshhjacobson** [comment]
Update: This issue is directly related to the parcoords issue BigFatDog/parcoords-es#26. I will follow up with them soon to get this sorted out.

**Comment by wraseman** [comment]
During beta testing, Jacob pointed out an issue with ```.cluster({hidden})```. I think this is related to the hide/show axes problems. We should check that ```.cluster()``` works properly once the bug discussed on this thread has been fixed.

**Comment by wraseman** [comment]
@joshhjacobson, unfortunately, this issue still seems to make .setAxesLayout() unusable even with the latest changes to Parcoords. Check out the axes_layout.html as an example. The following plots (the 2nd and 3rd plot, overall) should have four and three axes (as seen in the code):
![image](https://user-images.githubusercontent.com/14048152/51947522-6d9b8300-23e2-11e9-979c-a549515702ed.png)

However, the 2nd plot contains axes for each data column and the 3rd plot is largely unresponsive. 

![image](https://user-images.githubusercontent.com/14048152/51947495-5197e180-23e2-11e9-8c85-62aad2206005.png)

Thoughts?

**Comment by joshhjacobson** [comment]
The original issue with `hideAxis` which produced the error `Cannot read 'type' of undefined` has been resolved in Parcoords [v2.2.7](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.2.7). 

There are still lingering issues in Parcoords that effect that effect `hideAxes` and `setAxesLayout`, but these will be addressed in separately.

**Comment by wraseman** [comment]
@joshhjacobson, I've updated the github.io page with v1.0.2 of parasol.standalone.js, but it seems like the hidden axis issue is still there (see [https://parasoljs.github.io/demo/cluster.html](https://parasoljs.github.io/demo/cluster.html) as an example). Any thoughts on why this might be?
